{
   "assignee" : null,
   "body" : "One of my nodes on master was catching up with the block chain (~200 blocks behind) and triggered the following error, which remained even after maintaining sync with the network for a few hours. Misfiring is understandable, leaving it lingering after catching up feels a little buggy. Error was cleared after a restart.\r\n\r\n    {\r\n    ...\r\n      \"blocks\": 359934,\r\n    ...\r\n      \"connections\": 8,\r\n    ...\r\n      \"errors\": \"WARNING: check your network connection, 0 blocks received in the last 4 hours (24 expected)\"\r\n    }\r\n",
   "closed_at" : null,
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
      "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
      "followers_url" : "https://api.github.com/users/laanwj/followers",
      "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
      "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/laanwj",
      "id" : 126646,
      "login" : "laanwj",
      "organizations_url" : "https://api.github.com/users/laanwj/orgs",
      "received_events_url" : "https://api.github.com/users/laanwj/received_events",
      "repos_url" : "https://api.github.com/users/laanwj/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/laanwj"
   },
   "comments" : 8,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6251/comments",
   "created_at" : "2015-06-08T04:57:13Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6251/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/6251",
   "id" : 86026234,
   "labels" : [
      {
         "color" : "006b75",
         "name" : "P2P",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/P2P"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6251/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "number" : 6251,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "title" : "Falsely triggered \"check your network connection\" error while catching up. ",
   "updated_at" : "2016-02-09T17:27:57Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6251",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/12791744?v=3",
      "events_url" : "https://api.github.com/users/chronicbitcoin/events{/privacy}",
      "followers_url" : "https://api.github.com/users/chronicbitcoin/followers",
      "following_url" : "https://api.github.com/users/chronicbitcoin/following{/other_user}",
      "gists_url" : "https://api.github.com/users/chronicbitcoin/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/chronicbitcoin",
      "id" : 12791744,
      "login" : "chronicbitcoin",
      "organizations_url" : "https://api.github.com/users/chronicbitcoin/orgs",
      "received_events_url" : "https://api.github.com/users/chronicbitcoin/received_events",
      "repos_url" : "https://api.github.com/users/chronicbitcoin/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/chronicbitcoin/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/chronicbitcoin/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/chronicbitcoin"
   }
}
