[
   {
      "body" : "Thanks for reporting, I was not able to reproduce either. ",
      "created_at" : "2016-05-24T18:22:47Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8096#issuecomment-221359642",
      "id" : 221359642,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8096",
      "updated_at" : "2016-05-24T18:22:47Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/221359642",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=3",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "body" : "I'm also not able to reproduce this, but can reproduce this very often (0.1 probability):\r\n\r\n```\r\nInitializing test directory /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testeqexi0jw\r\nUnexpected exception caught during testing: timeout('timed out',)\r\n  File \"/private/tmp/bitcoin-master/qa/rpc-tests/test_framework/test_framework.py\", line 140, in main\r\n    self.setup_network()\r\n  File \"./sendheaders.py\", line 218, in setup_network\r\n    self.nodes = start_nodes(self.num_nodes, self.options.tmpdir, [[\"-debug\", \"-logtimemicros=1\"]]*2)\r\n  File \"/private/tmp/bitcoin-master/qa/rpc-tests/test_framework/util.py\", line 323, in start_nodes\r\n    rpcs.append(start_node(i, dirname, extra_args[i], rpchost, binary=binary[i]))\r\n  File \"/private/tmp/bitcoin-master/qa/rpc-tests/test_framework/util.py\", line 304, in start_node\r\n    wait_for_bitcoind_start(bitcoind_processes[i], url, i)\r\n  File \"/private/tmp/bitcoin-master/qa/rpc-tests/test_framework/util.py\", line 177, in wait_for_bitcoind_start\r\n    blocks = rpc.getblockcount()\r\n  File \"/private/tmp/bitcoin-master/qa/rpc-tests/test_framework/coverage.py\", line 49, in __call__\r\n    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n  File \"/private/tmp/bitcoin-master/qa/rpc-tests/test_framework/authproxy.py\", line 137, in __call__\r\n    response = self._request('POST', self.__url.path, postdata)\r\n  File \"/private/tmp/bitcoin-master/qa/rpc-tests/test_framework/authproxy.py\", line 118, in _request\r\n    self.__conn.request(method, path, postdata, headers)\r\n  File \"/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 1083, in request\r\n    self._send_request(method, url, body, headers)\r\n  File \"/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 1128, in _send_request\r\n    self.endheaders(body)\r\n  File \"/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 1079, in endheaders\r\n    self._send_output(message_body)\r\n  File \"/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 911, in _send_output\r\n    self.send(msg)\r\n  File \"/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 854, in send\r\n    self.connect()\r\n  File \"/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 826, in connect\r\n    (self.host,self.port), self.timeout, self.source_address)\r\n  File \"/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py\", line 711, in create_connection\r\n    raise err\r\n  File \"/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py\", line 702, in create_connection\r\n    sock.connect(sa)\r\nStopping nodes\r\nTraceback (most recent call last):\r\n  File \"./sendheaders.py\", line 518, in <module>\r\n    SendHeadersTest().main()\r\n  File \"/private/tmp/bitcoin-master/qa/rpc-tests/test_framework/test_framework.py\", line 164, in main\r\n    wait_bitcoinds()\r\n  File \"/private/tmp/bitcoin-master/qa/rpc-tests/test_framework/util.py\", line 355, in wait_bitcoinds\r\n    bitcoind.wait(timeout=BITCOIND_PROC_WAIT_TIMEOUT)\r\n  File \"/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py\", line 1643, in wait\r\n    raise TimeoutExpired(self.args, timeout)\r\nsubprocess.TimeoutExpired: Command '['bitcoind', '-datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testeqexi0jw/node1', '-server', '-keypool=1', '-discover=0', '-rest', '-mocktime=0', '-debug', '-logtimemicros=1']' timed out after 60 seconds\r\n```",
      "created_at" : "2016-05-24T19:14:44Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8096#issuecomment-221373849",
      "id" : 221373849,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8096",
      "updated_at" : "2016-05-24T19:14:44Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/221373849",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6848764?v=3",
         "events_url" : "https://api.github.com/users/paveljanik/events{/privacy}",
         "followers_url" : "https://api.github.com/users/paveljanik/followers",
         "following_url" : "https://api.github.com/users/paveljanik/following{/other_user}",
         "gists_url" : "https://api.github.com/users/paveljanik/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/paveljanik",
         "id" : 6848764,
         "login" : "paveljanik",
         "organizations_url" : "https://api.github.com/users/paveljanik/orgs",
         "received_events_url" : "https://api.github.com/users/paveljanik/received_events",
         "repos_url" : "https://api.github.com/users/paveljanik/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/paveljanik/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/paveljanik/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/paveljanik"
      }
   },
   {
      "body" : "Was triggered in travis in #9246 (which has no code changes). Fails at a different stage than the ones above so may be a different issue.\r\n```\r\nsendheaders.py:\r\nInitializing test directory /tmp/testmyq6oa3l/319\r\nstart_node: bitcoind started, waiting for RPC to come up\r\nstart_node: RPC successfully started\r\nstart_node: bitcoind started, waiting for RPC to come up\r\nstart_node: RPC successfully started\r\nMiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:13552\r\nMiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:13552\r\nPart 1: headers don't start before sendheaders message...\r\nAssertion failed: False != True\r\nStopping nodes\r\nNot cleaning up dir /tmp/testmyq6oa3l/319\r\nFailed\r\n\r\nstderr:\r\n  File \"/home/travis/build/bitcoin/bitcoin/qa/rpc-tests/test_framework/test_framework.py\", line 145, in main\r\n    self.run_test()\r\n  File \"/home/travis/build/bitcoin/bitcoin/build/../qa/rpc-tests/sendheaders.py\", line 291, in run_test\r\n    assert_equal(inv_node.check_last_announcement(inv=[tip]), True)\r\n  File \"/home/travis/build/bitcoin/bitcoin/qa/rpc-tests/test_framework/util.py\", line 529, in assert_equal\r\n    raise AssertionError(\"%s != %s\"%(str(thing1),str(thing2)))\r\nPass: False, Duration: 4 s\r\n```",
      "created_at" : "2016-11-30T09:45:44Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8096#issuecomment-263828728",
      "id" : 263828728,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8096",
      "updated_at" : "2016-11-30T09:45:44Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/263828728",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   },
   {
      "body" : "@laanwj, is there a link to the failing travis run? The only run I see related to #9246 in the last 14 days at https://travis-ci.org/bitcoin/bitcoin/pull_requests seems to have finished successfully.\r\n\r\nI just tried running `sendheaders.py` myself in a loop on travis. It ran 328 times with no failures before timing out: https://travis-ci.org/ryanofsky/bitcoin/builds/180127519",
      "created_at" : "2016-11-30T17:06:54Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8096#issuecomment-263931835",
      "id" : 263931835,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8096",
      "updated_at" : "2016-11-30T17:06:54Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/263931835",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/7133040?v=3",
         "events_url" : "https://api.github.com/users/ryanofsky/events{/privacy}",
         "followers_url" : "https://api.github.com/users/ryanofsky/followers",
         "following_url" : "https://api.github.com/users/ryanofsky/following{/other_user}",
         "gists_url" : "https://api.github.com/users/ryanofsky/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/ryanofsky",
         "id" : 7133040,
         "login" : "ryanofsky",
         "organizations_url" : "https://api.github.com/users/ryanofsky/orgs",
         "received_events_url" : "https://api.github.com/users/ryanofsky/received_events",
         "repos_url" : "https://api.github.com/users/ryanofsky/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/ryanofsky/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/ryanofsky/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/ryanofsky"
      }
   },
   {
      "body" : "The travis link was invalidated when I restarted the build.\n",
      "created_at" : "2016-11-30T18:15:59Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8096#issuecomment-263950439",
      "id" : 263950439,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8096",
      "updated_at" : "2016-11-30T18:15:59Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/263950439",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   }
]
