{
   "assignee" : null,
   "assignees" : [],
   "body" : "After long time, I'm trying to pass all the tests. Using current master:\r\n\r\n```\r\nfor par in 1 2 4\r\ndo\r\n   for round in 1 2 3 4 5 6 7 8 9 10\r\n   do\r\n      echo Par: $par, round: $round\r\n      rm -rf qa/cache/; qa/pull-tester/rpc-tests.py -parallel=$par > round-$par-$round.log 2>&1\r\n   done\r\ndone\r\n```\r\n\r\nAnd I'm not able to pass the testsuite completely.\r\n\r\nOn OS X, the testsuite fails randomly with:\r\n\r\n```\r\nError: Unable to start HTTP server. See debug log for details.\r\n```\r\n\r\nThe `debug.log` of one node then contains something like:\r\n\r\n```\r\n2016-12-10 21:21:34 Binding RPC on address ::1 port 17082 failed.\r\n2016-12-10 21:21:34 Binding RPC on address 127.0.0.1 port 17082 failed.\r\n```\r\n\r\nI have read in other issues (https://github.com/bitcoin/bitcoin/issues/8425#issuecomment-238127542), that the default to run 4 tests in parallel can cause some issues, so I have tried to isolate this issue by removing the parallelisation. But it did not helped completely, but the frequency of such failures is definitely small with less parallelism...\r\n\r\nI will post detailed results and analyse of the above script tomorrow.\r\n\r\nSimilar issue was reported by @fanquake at https://github.com/bitcoin/bitcoin/issues/8425#issuecomment-236474724\r\n\r\nOne of my favourite failure is:\r\n\r\n```\r\nInitializing test directory /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testye4vq40s/424\r\nMining blocks...\r\nAssertion failed: 0E-8 != 53.99954800\r\nStopping nodes\r\nNot cleaning up dir /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testye4vq40s/424\r\nFailed\r\n\r\nstderr:\r\nError: Unable to start HTTP server. See debug log for details.\r\n  File \"/private/tmp/bitcoin-master/qa/rpc-tests/test_framework/test_framework.py\", line 145, in main\r\n    self.run_test()\r\n  File \"/tmp/bitcoin-master/qa/rpc-tests/wallet.py\", line 212, in run_test\r\n    assert_equal(self.nodes[2].getbalance(), node_2_bal) #should not be changed because tx was not broadcasted\r\n  File \"/private/tmp/bitcoin-master/qa/rpc-tests/test_framework/util.py\", line 529, in assert_equal\r\n    raise AssertionError(\"%s != %s\"%(str(thing1),str(thing2)))\r\n```\r\n",
   "closed_at" : "2017-05-15T14:10:33Z",
   "closed_by" : {
      "avatar_url" : "https://avatars1.githubusercontent.com/u/6848764?v=3",
      "events_url" : "https://api.github.com/users/paveljanik/events{/privacy}",
      "followers_url" : "https://api.github.com/users/paveljanik/followers",
      "following_url" : "https://api.github.com/users/paveljanik/following{/other_user}",
      "gists_url" : "https://api.github.com/users/paveljanik/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/paveljanik",
      "id" : 6848764,
      "login" : "paveljanik",
      "organizations_url" : "https://api.github.com/users/paveljanik/orgs",
      "received_events_url" : "https://api.github.com/users/paveljanik/received_events",
      "repos_url" : "https://api.github.com/users/paveljanik/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/paveljanik/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/paveljanik/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/paveljanik"
   },
   "comments" : 16,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/9317/comments",
   "created_at" : "2016-12-10T21:55:22Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/9317/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/9317",
   "id" : 194796495,
   "labels" : [
      {
         "color" : "d4c5f9",
         "default" : false,
         "id" : 62963516,
         "name" : "Tests",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/9317/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "number" : 9317,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "rpc-tests.py: Too many \"Error: Unable to start HTTP server. See debug log for details.\"",
   "updated_at" : "2017-05-15T14:10:33Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/9317",
   "user" : {
      "avatar_url" : "https://avatars1.githubusercontent.com/u/6848764?v=3",
      "events_url" : "https://api.github.com/users/paveljanik/events{/privacy}",
      "followers_url" : "https://api.github.com/users/paveljanik/followers",
      "following_url" : "https://api.github.com/users/paveljanik/following{/other_user}",
      "gists_url" : "https://api.github.com/users/paveljanik/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/paveljanik",
      "id" : 6848764,
      "login" : "paveljanik",
      "organizations_url" : "https://api.github.com/users/paveljanik/orgs",
      "received_events_url" : "https://api.github.com/users/paveljanik/received_events",
      "repos_url" : "https://api.github.com/users/paveljanik/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/paveljanik/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/paveljanik/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/paveljanik"
   }
}
