{
   "assignee" : null,
   "body" : "Hi everybody.\r\n\r\nI searched for duplicates for this issue but I couldn't manage to find any, both on this repo and on Google. It happens with Bitcoin Core v0.11.2 on Windows (current environment : Windows 10 x64) and seems to happen randomly some time during sync start, never immediately. The problem is a total crash of the program. I can relaunch it to keep syncing but it slows it down quite a lot - I can't leave it on overnight. I'll get throught it but I found it interesting to share this report with you.\r\n\r\n**What I do**\r\nI launch Bitcoin Core.\r\n\r\n**What does happen**\r\nIt resumes syncing to get the full blockchain, nothing bad happens at this moment. Then, several hours later, a seemingly random error throws in : an error windows appears, describing a fatal error that will lead to program shutdown. Closing this windows terminates the program.\r\n\r\n**What happens then**\r\nI can restart the program, it will resume syncing. Then you can go back to \"What does happen\" because the same error happens again after a few hours.\r\n\r\n**Context data**\r\nThis happens on Windows 10 x64. The program (v0.11.2 - x64) was downloaded from bitcoin.org.\r\nThis doesn't seem to be a network-related issue, it happens on very different network contexts.\r\n\r\n**Relevant log**\r\n```\r\n2015-12-22 18:58:41 IO error: Win32WritableFile.Sync::FlushFileBuffers C:\\Users\\Username\\AppData\\Roaming\\Bitcoin\\chainstate\\223994.ldb: MÃÂ©dia protÃÂ©gÃÂ© en ÃÂ©criture. [it means the media is not writeable]\r\n2015-12-22 18:58:41 *** System error while flushing: Database I/O error\r\n2015-12-22 19:16:21 ping timeout: 1200.023628s\r\n2015-12-22 19:17:59 socket sending timeout: 1201s\r\n2015-12-22 19:18:39 socket sending timeout: 1201s\r\n2015-12-22 19:18:39 socket sending timeout: 1201s\r\n2015-12-22 19:18:40 socket sending timeout: 1201s\r\n2015-12-22 19:18:40 socket sending timeout: 1201s\r\n2015-12-22 19:18:40 socket sending timeout: 1201s\r\n2015-12-22 19:18:40 socket sending timeout: 1201s\r\n\r\n[I think that at this moment I came back to my computer, noticed the error windows, closed it and restarted the program]\r\n\r\n2015-12-22 22:56:19 ERROR: ProcessNewBlock: ActivateBestChain failed\r\n2015-12-22 22:56:20 opencon thread interrupt\r\n2015-12-22 22:56:20 scheduler thread interrupt\r\n2015-12-22 22:56:20 addcon thread interrupt\r\n2015-12-22 22:56:20 msghand thread interrupt\r\n2015-12-22 22:56:20 net thread interrupt\r\n2015-12-22 22:56:20 Shutdown: In progress...\r\n2015-12-22 22:56:20 StopNode()\r\n2015-12-22 22:56:20 IO error: Win32WritableFile.Sync::FlushFileBuffers C:\\Users\\Username\\AppData\\Roaming\\Bitcoin\\chainstate\\223994.ldb: MÃÂ©dia protÃÂ©gÃÂ© en ÃÂ©criture.\r\n2015-12-22 22:56:20 *** System error while flushing: Database I/O error\r\n2015-12-22 22:56:21 Shutdown: done\r\n2015-12-22 22:56:23 GUI: \"registerShutdownBlockReason: Successfully registered: Bitcoin Core didn't yet exit safely...\"\r\n2015-12-22 22:56:23 \r\n```\r\n\r\nThanks in advance for any answer! :)\r\n\r\nEDIT : Of course the path written in debug logs *is* writeable and its nature isn't supposed to change over time.",
   "closed_at" : "2015-12-26T04:18:07Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/16407415?v=3",
      "events_url" : "https://api.github.com/users/Ano59/events{/privacy}",
      "followers_url" : "https://api.github.com/users/Ano59/followers",
      "following_url" : "https://api.github.com/users/Ano59/following{/other_user}",
      "gists_url" : "https://api.github.com/users/Ano59/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/Ano59",
      "id" : 16407415,
      "login" : "Ano59",
      "organizations_url" : "https://api.github.com/users/Ano59/orgs",
      "received_events_url" : "https://api.github.com/users/Ano59/received_events",
      "repos_url" : "https://api.github.com/users/Ano59/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/Ano59/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/Ano59/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/Ano59"
   },
   "comments" : 5,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/7248/comments",
   "created_at" : "2015-12-23T00:29:03Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/7248/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/7248",
   "id" : 123581022,
   "labels" : [
      {
         "color" : "f7c6c7",
         "name" : "Data corruption",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Data%20corruption"
      },
      {
         "color" : "fbca04",
         "name" : "UTXO Db and Indexes",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/UTXO%20Db%20and%20Indexes"
      },
      {
         "color" : "884400",
         "name" : "Windows",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Windows"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/7248/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "number" : 7248,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "[0.11.2] Random crashes during blockchain sync - Windows - I/O error",
   "updated_at" : "2016-03-03T13:34:11Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/7248",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/16407415?v=3",
      "events_url" : "https://api.github.com/users/Ano59/events{/privacy}",
      "followers_url" : "https://api.github.com/users/Ano59/followers",
      "following_url" : "https://api.github.com/users/Ano59/following{/other_user}",
      "gists_url" : "https://api.github.com/users/Ano59/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/Ano59",
      "id" : 16407415,
      "login" : "Ano59",
      "organizations_url" : "https://api.github.com/users/Ano59/orgs",
      "received_events_url" : "https://api.github.com/users/Ano59/received_events",
      "repos_url" : "https://api.github.com/users/Ano59/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/Ano59/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/Ano59/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/Ano59"
   }
}
