[
   {
      "body" : "Concept ACK, this is by far the most straightforward solution, if there is no need for platform-specific exceptions then let's avoid them.",
      "created_at" : "2016-09-29T11:02:23Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8834#issuecomment-250435481",
      "id" : 250435481,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8834",
      "updated_at" : "2016-09-29T11:02:23Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/250435481",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   },
   {
      "body" : "Interesting, apparently this causes the NULLDUMMY test to fail during close, on some platforms. I don't understand why this file would suddenly be missing during close:\r\n```\r\nstderr:\r\nException ignored in: <bound method _Database.close of <dbm.dumb._Database object at 0x7f8f097f1be0>>\r\nTraceback (most recent call last):\r\n  File \"/usr/lib/python3.4/dbm/dumb.py\", line 250, in close\r\n    self._commit()\r\n  File \"/usr/lib/python3.4/dbm/dumb.py\", line 112, in _commit\r\n    with self._io.open(self._dirfile, 'w', encoding=\"Latin-1\") as f:\r\nFileNotFoundError: [Errno 2] No such file or directory: '/tmp/testkz7n1z0q/1/blocks.dir'\r\nException ignored in: <bound method _Database.close of <dbm.dumb._Database object at 0x7f8f097f1d68>>\r\nTraceback (most recent call last):\r\n  File \"/usr/lib/python3.4/dbm/dumb.py\", line 250, in close\r\n    self._commit()\r\n  File \"/usr/lib/python3.4/dbm/dumb.py\", line 112, in _commit\r\n    with self._io.open(self._dirfile, 'w', encoding=\"Latin-1\") as f:\r\nFileNotFoundError: [Errno 2] No such file or directory: '/tmp/testkz7n1z0q/1/transactions.dir'\r\n```\r\nI can reproduce this locally on FreeBSD.\r\nAre perhaps the database files wiped before closing it?\r\nThis only affects nulldummy.py not the other tests involving block stores.",
      "created_at" : "2016-09-29T11:53:33Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8834#issuecomment-250445328",
      "id" : 250445328,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8834",
      "updated_at" : "2016-09-29T12:55:19Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/250445328",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   },
   {
      "body" : "Failed on my OSX machine:\r\n\r\n```\r\ntime qa/pull-tester/rpc-tests.py p2p-fullblocktest\r\n.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................\r\np2p-fullblocktest.py:\r\nInitializing test directory /var/folders/hp/kb9p9q8x4k3_z_ccy588hxrc0000gn/T/test7n1apn12/0\r\nMiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11000\r\nTest 1: PASS [1]\r\nTest 2: PASS [100]\r\nTest 3: PASS [101]\r\nTest 4: PASS [102]\r\nTest 5: PASS [102]\r\nTest 6: PASS [103]\r\nTest 7: PASS [103]\r\nTest 8: PASS [104]\r\nTest 9: PASS [104]\r\nTest 10: PASS [104]\r\nTest 11: PASS [104]\r\nTest 12: PASS [104]\r\nTest 13: PASS [104]\r\nTest 14: PASS [104]\r\nTest 15: PASS [104]\r\nTest 16: PASS [105]\r\nTest 17: PASS [106]\r\nTest 18: PASS [106]\r\nTest 19: PASS [106]\r\nTest 20: PASS [106]\r\nTest 21: PASS [106]\r\nTest 22: PASS [106]\r\nTest 23: PASS [106]\r\nTest 24: PASS [106]\r\nTest 25: PASS [107]\r\nTest 26: PASS [107]\r\nTest 27: PASS [107]\r\nTest 28: PASS [107]\r\nTest 29: PASS [107]\r\nTest 30: PASS [107]\r\nTest 31: PASS [107]\r\nTest 32: PASS [108]\r\nTest 33: PASS [109]\r\nTest 34: PASS [109]\r\nTest 35: PASS [110]\r\nTest 36: PASS [110]\r\nTest 37: PASS [111]\r\nTest 38: PASS [111]\r\nTest 39: PASS [111]\r\nTest 40: PASS [111]\r\nTest 41: PASS [112]\r\nTest 42: PASS [112]\r\nTest 43: PASS [113]\r\nTest 44: PASS [113]\r\nTest 45: PASS [114]\r\nTest 46: PASS [115]\r\nTest 47: PASS [115]\r\nTest 48: PASS [115]\r\nTest 49: PASS [115]\r\nTest 50: PASS [115]\r\nTest 51: PASS [115]\r\nTest 52: PASS [115]\r\nTest 53: PASS [115]\r\nTest 54: PASS [115]\r\nTest 55: PASS [115]\r\nTest 56: PASS [115]\r\nTest 57: PASS [116]\r\nTest 58: PASS [116]\r\nTest 59: PASS [116]\r\nTest 60: PASS [117]\r\nTest 61: PASS [117]\r\nTest 62: PASS [117]\r\nTest 63: PASS [117]\r\nTest 64: PASS [118]\r\nTest 65: PASS [118]\r\nTest 66: PASS [118]\r\nTest 67: PASS [118]\r\nTest 68: PASS [118]\r\nTest 69: PASS [119]\r\nTest 70: PASS [120]\r\nTest 71: PASS [120]\r\nTest 72: PASS [120]\r\nTest 73: PASS [120]\r\nTest 74: PASS [121]\r\nTest 75: PASS [121]\r\nTest 76: PASS [121]\r\nTest 77: PASS [122]\r\nTest 78: PASS [122]\r\nTest 79: PASS [122]\r\nTest 80: PASS [123]\r\nTest 81: PASS [124]\r\nTest 82: PASS [125]\r\nTest 83: PASS [126]\r\nTest 84: PASS [127]\r\nTest 85: PASS [127]\r\nTest 86: PASS [127]\r\nTest 87: PASS [128]\r\nTest 88: PASS [129]\r\nTest 89: PASS [130]\r\nTest 90: PASS [130]\r\nTest 91: PASS [131]\r\nTest 92: PASS [131]\r\nTest 93: PASS [132]\r\nTest 94: PASS [132]\r\nTest 95: PASS [1220]\r\nTest 96: PASS [1220]\r\nTest 97: PASS [1221]\r\nTest 98: PASS [1221]\r\nUnexpected exception caught during testing: ConnectionResetError(54, 'Connection reset by peer')\r\nStopping nodes\r\nNot cleaning up dir /var/folders/hp/kb9p9q8x4k3_z_ccy588hxrc0000gn/T/test7n1apn12/0\r\nFailed\r\n\r\nstderr:\r\n  File \"/Users/jonasschnelli/Documents/bitcoin/bitcoin/qa/rpc-tests/test_framework/test_framework.py\", line 151, in main\r\n    self.run_test()\r\n  File \"/Users/jonasschnelli/Documents/bitcoin/bitcoin/qa/rpc-tests/p2p-fullblocktest.py\", line 73, in run_test\r\n    self.test.run()\r\n  File \"/Users/jonasschnelli/Documents/bitcoin/bitcoin/qa/rpc-tests/test_framework/comptool.py\", line 395, in run\r\n    print(\"Test %d: PASS\" % test_number, [ c.rpc.getblockcount() for c in self.connections ])\r\n  File \"/Users/jonasschnelli/Documents/bitcoin/bitcoin/qa/rpc-tests/test_framework/comptool.py\", line 395, in <listcomp>\r\n    print(\"Test %d: PASS\" % test_number, [ c.rpc.getblockcount() for c in self.connections ])\r\n  File \"/Users/jonasschnelli/Documents/bitcoin/bitcoin/qa/rpc-tests/test_framework/coverage.py\", line 49, in __call__\r\n    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n  File \"/Users/jonasschnelli/Documents/bitcoin/bitcoin/qa/rpc-tests/test_framework/authproxy.py\", line 148, in __call__\r\n    response = self._request('POST', self.__url.path, postdata.encode('utf-8'))\r\n  File \"/Users/jonasschnelli/Documents/bitcoin/bitcoin/qa/rpc-tests/test_framework/authproxy.py\", line 125, in _request\r\n    return self._get_response()\r\n  File \"/Users/jonasschnelli/Documents/bitcoin/bitcoin/qa/rpc-tests/test_framework/authproxy.py\", line 163, in _get_response\r\n    http_response = self.__conn.getresponse()\r\n  File \"/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 1197, in getresponse\r\n    response.begin()\r\n  File \"/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 297, in begin\r\n    version, status, reason = self._read_status()\r\n  File \"/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 258, in _read_status\r\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\r\n  File \"/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py\", line 575, in readinto\r\n    return self._sock.recv_into(b)\r\n\r\nPass: False, Duration: 928 s\r\n\r\nTEST                 | PASSED | DURATION\r\n\r\np2p-fullblocktest.py | False  | 928 s\r\n\r\nALL                  | False  | 928 s (accumulated)\r\n\r\nRuntime: 928 s\r\n\r\nreal\t15m28.427s\r\nuser\t14m47.171s\r\nsys\t0m31.176s\r\n```\r\n\r\nTrying again....",
      "created_at" : "2016-09-29T12:05:05Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8834#issuecomment-250447599",
      "id" : 250447599,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8834",
      "updated_at" : "2016-09-29T12:05:05Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/250447599",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/178464?v=3",
         "events_url" : "https://api.github.com/users/jonasschnelli/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jonasschnelli/followers",
         "following_url" : "https://api.github.com/users/jonasschnelli/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jonasschnelli/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jonasschnelli",
         "id" : 178464,
         "login" : "jonasschnelli",
         "organizations_url" : "https://api.github.com/users/jonasschnelli/orgs",
         "received_events_url" : "https://api.github.com/users/jonasschnelli/received_events",
         "repos_url" : "https://api.github.com/users/jonasschnelli/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jonasschnelli/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jonasschnelli/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jonasschnelli"
      }
   },
   {
      "body" : "\"Connection reset by peer\" is a different issue, unrelated to the database. I have the same on FreeBSD. @jonasschnelli can you try:\r\n\r\n```patch\r\ndiff --git a/qa/rpc-tests/test_framework/authproxy.py b/qa/rpc-tests/test_framework/authproxy.py\r\nindex f5e0be2..fd7f32b 100644\r\n--- a/qa/rpc-tests/test_framework/authproxy.py\r\n+++ b/qa/rpc-tests/test_framework/authproxy.py\r\n@@ -130,8 +130,9 @@ class AuthServiceProxy(object):\r\n                 return self._get_response()\r\n             else:\r\n                 raise\r\n-        except BrokenPipeError:\r\n-            # Python 3.5+ raises this instead of BadStatusLine when the connection was reset\r\n+        except (BrokenPipeError,ConnectionResetError):\r\n+            # Python 3.5+ raises BrokenPipeError instead of BadStatusLine when the connection was reset\r\n+            # ConnectionResetError happens on FreeBSD with Python 3.4\r\n             self.__conn.close()\r\n             self.__conn.request(method, path, postdata, headers)\r\n             return self._get_response()\r\n```",
      "created_at" : "2016-09-29T12:19:12Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8834#issuecomment-250450213",
      "id" : 250450213,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8834",
      "updated_at" : "2016-09-29T12:20:20Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/250450213",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   },
   {
      "body" : "Passed after adding `ConnectionResetError`.\r\n```\r\ntime qa/pull-tester/rpc-tests.py p2p-fullblocktest\r\n.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................\r\np2p-fullblocktest.py:\r\nPass: True, Duration: 969 s\r\n\r\nTEST                 | PASSED | DURATION\r\n\r\np2p-fullblocktest.py | True   | 969 s\r\n\r\nALL                  | True   | 969 s (accumulated)\r\n\r\nRuntime: 969 s\r\n\r\nreal\t16m9.820s\r\nuser\t15m22.178s\r\nsys\t0m34.593s\r\n```",
      "created_at" : "2016-09-29T12:53:33Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8834#issuecomment-250457270",
      "id" : 250457270,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8834",
      "updated_at" : "2016-09-29T12:53:33Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/250457270",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/178464?v=3",
         "events_url" : "https://api.github.com/users/jonasschnelli/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jonasschnelli/followers",
         "following_url" : "https://api.github.com/users/jonasschnelli/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jonasschnelli/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jonasschnelli",
         "id" : 178464,
         "login" : "jonasschnelli",
         "organizations_url" : "https://api.github.com/users/jonasschnelli/orgs",
         "received_events_url" : "https://api.github.com/users/jonasschnelli/received_events",
         "repos_url" : "https://api.github.com/users/jonasschnelli/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jonasschnelli/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jonasschnelli/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jonasschnelli"
      }
   },
   {
      "body" : "> Interesting, apparently this causes the NULLDUMMY test to fail during close, on some platforms. I don't understand why this file would suddenly be missing during close:\r\n\r\nUnrelated to this pull, but needs travis retriggered after #8835",
      "created_at" : "2016-09-29T13:37:42Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8834#issuecomment-250468062",
      "id" : 250468062,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8834",
      "updated_at" : "2016-09-29T13:37:42Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/250468062",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=3",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "body" : "> Unrelated to this pull, but needs travis retriggered after #8835\r\n\r\nDone",
      "created_at" : "2016-09-29T14:46:56Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8834#issuecomment-250488003",
      "id" : 250488003,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8834",
      "updated_at" : "2016-09-29T14:46:56Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/250488003",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   },
   {
      "body" : "Tested ACK https://github.com/bitcoin/bitcoin/pull/8834/commits/fa9cd25ed0587078e3218965606c79ebf8138d53",
      "created_at" : "2016-09-29T15:22:51Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8834#issuecomment-250498709",
      "id" : 250498709,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8834",
      "updated_at" : "2016-09-29T15:22:51Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/250498709",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   }
]
