[
   {
      "body" : "I'm able to reproduce this error in the log by enabling `debug=net` and sending an invalid inv type:\r\n```\r\n2016-11-09 09:40:27 \r\n\r\n************************\r\nEXCEPTION: St12out_of_range       \r\nCInv::GetCommand(): type=666 unknown type       \r\nbitcoin in ProcessMessages()       \r\n\r\n2016-11-09 09:40:27 ProcessMessages(inv, 37 bytes) FAILED peer=7\r\n```\r\nHowever the exception is caught and printed, the process does not crash. It also appears without `debug=net`.\r\n\r\nHaving a `ToString` function raise an exception is kind of unexpected. I think we should change CInv::ToString to catch the exception and return something like `unknown: %d` instead, for better troubleshooting. But it does not result in a crash right now.\r\n",
      "created_at" : "2016-11-09T09:41:38Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/9110#issuecomment-259372006",
      "id" : 259372006,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/9110",
      "updated_at" : "2016-11-09T09:58:38Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/259372006",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   },
   {
      "body" : "@rebroad: so what \"to cause the program to end?\"? Was it some local change on your side? Did `bitcoind` really stopped at all?\r\n",
      "created_at" : "2016-11-09T10:35:18Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/9110#issuecomment-259383221",
      "id" : 259383221,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/9110",
      "updated_at" : "2016-11-09T10:35:18Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/259383221",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6848764?v=3",
         "events_url" : "https://api.github.com/users/paveljanik/events{/privacy}",
         "followers_url" : "https://api.github.com/users/paveljanik/followers",
         "following_url" : "https://api.github.com/users/paveljanik/following{/other_user}",
         "gists_url" : "https://api.github.com/users/paveljanik/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/paveljanik",
         "id" : 6848764,
         "login" : "paveljanik",
         "organizations_url" : "https://api.github.com/users/paveljanik/orgs",
         "received_events_url" : "https://api.github.com/users/paveljanik/received_events",
         "repos_url" : "https://api.github.com/users/paveljanik/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/paveljanik/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/paveljanik/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/paveljanik"
      }
   }
]
